version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "1234:1234"
    environment:
      DATABASE_URL: postgres://albin:dessi@db:5432/olivvver
    depends_on:
      - db
    volumes:
      - ./server:/server
    links:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: albin
      POSTGRES_PASSWORD: dessi
      POSTGRES_DB: olivvver
