version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - server
      - db
    volumes:
      - ./frontend:/frontend
    links:
      - server
    env_file:
      - .env

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DATABASE_URL: postgres://root:abc123@db:5432/db_1
    depends_on:
      - db
    volumes:
      - ./server:/server
    links:
      - db
    env_file:
      - .env

  db:
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: "${PG_USER}"
    #   POSTGRES_PASSWORD: "${PG_PASSWORD}"
    #   POSTGRES_DB: "${PG_DB}"
